base_url = "https://wantguns.dev"
description = "Gunwant Jain's (@wantguns) place in the internet"
title = "Gunwant Jain - @wantguns"

compile_sass = true
generate_feed = true

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
extra_syntaxes_and_themes = [
  "highlight_theme",
]

highlight_code = true
highlight_theme = "base16-black-metal-bathory"

[extra]
author = "Gunwant Jain"
keywords = "Gunwant Jain, wantguns, Gunwant, WantGuns"
seo = true

nav_links = [
  {url = "$BASE_URL", name = "about"},
  {url = "$BASE_URL/blog", name = "blog"},
  {url = "$BASE_URL/projects", name = "projects"},
  {url = "https://bin.wantguns.dev/cv", name = "resume"},
  {url = "$BASE_URL/atom.xml", name = "rss"},
]
